title: Sarah-Louise Alsop
description: ""
footer_text: Copyright 2020 Sarah-Louise Alsop
header_feature_image: ../uploads/20160916_185432.jpg
header_text: Sarah-Louise Alsop
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/img_20200926_105050_977.jpg
favicon: ../uploads/img_20200926_105050_977.jpg
gridlayout: true
fixednavbar: false
upzoom: true
